escola_de_musica/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as view
from django.conf.urls.static import static
from core import views
from escola_de_musica import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin:index'),
    path('', views.IndexView.as_view(), name='home'),
    path('sinfonia/', include('sinfonia.urls')),
    path('instrumentos/', include('instrumento.urls')),
    path('orquestras/', include('orquestra.urls')),
    path('apresentacoes/', include('apresentacao.urls')),
    path('musico/', include('musico.urls')),
    path('registrar/', views.registrar, name='registrar'),
    path('login/', views.logar, name='login'),
    path('logout/', view.LogoutView.as_view(next_page='home'), name='logout'),
    path('sobre/', views.SobreView.as_view(), name='sobre'),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instrumento/urls.py
from django.urls import path
from instrumento import views

app_name = 'instrumento'

urlpatterns = [
    path('listar/', views.InstrumentoListView.as_view(), name='read'),
    path('criar/', views.InstrumentoCreateView.as_view(), name='create'),
    path('editar/<int:pk>/', views.InstrumentoUpdateView.as_view(), name='update'),
    path('excluir/<int:pk>/', views.InstrumentoDeleteView.as_view(), name='delete'),
]

musico/urls.py
from django.urls import path
from musico import views

app_name = 'musico'

urlpatterns = [
    path('listar/', views.MusicoListView.as_view(), name='read'),
    path('criar/', views.MusicoCreateView.as_view(), name='create'),
    path('editar/<int:pk>/', views.MusicoUpdateView.as_view(), name='update'),
    path('excluir/<int:pk>/', views.MusicoDeleteView.as_view(), name='delete'),
]

instrumento/models.py
from django.db import models

# Create your models here.

instrumento/views.py
from django.urls import reverse_lazy
from core.models import Instrumento
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

class InstrumentoListView(LoginRequiredMixin, ListView):
    model = Instrumento
    template_name = 'instrumento/tabela_instrumento.html'
    context_object_name = 'instrumentos'
    login_url='login'

class InstrumentoCreateView(LoginRequiredMixin, CreateView):
    model = Instrumento
    template_name = 'Instrumento/criar_Instrumento.html'
    fields = ['nome', 'marca', 'modelo', 'n_serie', 'musico']
    success_url = reverse_lazy('instrumento:read')
    login_url='login'

class InstrumentoUpdateView(LoginRequiredMixin, UpdateView):
    model = Instrumento
    template_name = 'instrumento/criar_instrumento.html'
    fields = ['nome', 'marca', 'modelo', 'n_serie', 'musico']
    success_url = reverse_lazy('instrumento:read')
    slug_field = 'id'
    login_url='login'

class InstrumentoDeleteView(LoginRequiredMixin, DeleteView):
    model = Instrumento
    success_url = reverse_lazy('instrumento:read')
    login_url='login'
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

instrumento/templates/instrumento/criar_instrumento.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}

<div class="col-12 d-flex flex-column align-items-center my-4">
    <div class="col-md-6">
        <h3 class="text-center mb-4">Instrumentos | {% if object %}Editar{% else %}Adicionar{% endif %}</h3>
    <div class="mt-4">
        <form method="post" action="{% if object %}{% url 'instrumento:update' object.pk %}{% else %}{% url 'instrumento:create' %}{% endif %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.nome.id_for_label }}">Nome</label>
                <input class="form-control" id="{{ form.nome.id_for_label }}" type="text"
                    placeholder="Nome" name="{{ form.nome.html_name }}" {% if form.nome.value %}
                    value="{{ form.nome.value }}" {% endif %}>
            </div>

            <div class="form-group">
                <label for="{{ form.marca.id_for_label }}">Marca</label>
                <input class="form-control" id="{{ form.marca.id_for_label }}" type="text"
                    placeholder="Marca" name="{{ form.marca.html_name }}" {% if form.marca.value %}
                    value="{{ form.marca.value }}" {% endif %}>
            </div>

            <div class="form-group">
                <label for="{{ form.modelo.id_for_label }}">Modelo</label>
                <input class="form-control" id="{{ form.modelo.id_for_label }}" type="text"
                    placeholder="Modelo" name="{{ form.modelo.html_name }}" {% if form.modelo.value %}
                    value="{{ form.modelo.value }}" {% endif %}>
            </div>

            <div class="form-group">
                <label for="{{ form.n_serie.id_for_label }}">N. Série</label>
                <input class="form-control" id="{{ form.n_serie.id_for_label }}" type="number" step="1"
                    placeholder="N. Série" name="{{ form.n_serie.html_name }}" {% if form.n_serie.value %}
                    value="{{ form.n_serie.value }}" {% endif %}>
            </div>

            <div class="form-group">
                <label for="{{ form.musico.id_for_label }}">Usado por</label>
                <select class="form-control" id="{{ form.musico.id_for_label }}" name="{{ form.musico.html_name }}">
                    {% for musico in form.musico.field.choices %}
                        <option value="{{ musico.0 }}" {% if musico.0 == form.musico.value %}selected{% endif %}>{{ musico.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="d-flex justify-content-between align-items-center">
                <a href="{% url 'instrumento:read' %}" class="btn btn-danger ml-3 cancelar-btn">Cancelar</a>
                <button type="submit" class="btn btn-primary salvar-btn">Salvar</button>
            </div>
        </form>
    </div>
    </div>
</div>

<style>
    .salvar-btn.btn-primary {
        background-color: #1b80eb; 
        border-color: #1b80eb;
    }
    
    .salvar-btn.btn-primary:hover {
        background-color: #11559e;
        border-color: #11559e;
    }

    .cancelar-btn.btn-danger {
        background-color: #e23a4b;
        border-color: #e23a4b;
    }

    .cancelar-btn.btn-danger:hover {
        background-color: #a82532;
        border-color: #a82532;
    }
</style>

{% endblock %}

instrumento/templates/instrumento/tabela_instrumento.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}
<style>
  .edit-btn {
    color: #1b80eb;
  }

  .edit-btn:hover {
    color: #11559e;
  }

  .delete-btn {
    color: #e23a4b;
  }

  .delete-btn:hover {
    color: #a82532;
  }
</style>
<div class="container table-container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Marca</th>
        <th scope="col">Modelo</th>
        <th scope="col">N. Série</th>
        <th scope="col">Usado por</th>
      </tr>
    </thead>
    <tbody>
      {% for isnt in instrumentos %}
      <tr>
        <td>{{ isnt.nome }}</td>
        <td>{{ isnt.marca }}</td>
        <td>{{ isnt.modelo }}</td>
        <td>{{ isnt.n_serie }}</td>
        <td>{{ isnt.musico }}</td>
        <td>
          <a href="{% url 'instrumento:update' isnt.id %}" class="btn btn-link edit-btn" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a href="{% url 'instrumento:delete' isnt.id %}" class="btn btn-link delete-btn" title="Excluir">
            <i class="fas fa-trash-alt"></i>
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="5" class="text-center">
          <h4>Nada aqui para ver</h4>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="col-12 d-flex justify-content-center mt-16">
    <a href="{% url 'instrumento:create' %}" class="btn sm action-2 f-16">Adicionar</a>
  </div>
</div>

{% endblock %}