apresentacao/urls.py
from django.urls import path
from apresentacao import views

app_name = 'apresentacao'

urlpatterns = [
    path('listar/', views.ApresentacaoListView.as_view(), name='read'),
    path('criar/', views.ApresentacaoCreateView.as_view(), name='create'),
    path('editar/<int:pk>/', views.ApresentacaoUpdateView.as_view(), name='update'),
    path('excluir/<int:pk>/', views.ApresentacaoDeleteView.as_view(), name='delete'),
]

escola_de_musica/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as view
from django.conf.urls.static import static
from core import views
from escola_de_musica import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin:index'),
    path('', views.IndexView.as_view(), name='home'),
    path('sinfonia/', include('sinfonia.urls')),
    path('instrumentos/', include('instrumento.urls')),
    path('orquestras/', include('orquestra.urls')),
    path('apresentacoes/', include('apresentacao.urls')),
    path('musico/', include('musico.urls')),
    path('registrar/', views.registrar, name='registrar'),
    path('login/', views.logar, name='login'),
    path('logout/', view.LogoutView.as_view(next_page='home'), name='logout'),
    path('sobre/', views.SobreView.as_view(), name='sobre'),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musico/urls.py
from django.urls import path
from musico import views

app_name = 'musico'

urlpatterns = [
    path('listar/', views.MusicoListView.as_view(), name='read'),
    path('criar/', views.MusicoCreateView.as_view(), name='create'),
    path('editar/<int:pk>/', views.MusicoUpdateView.as_view(), name='update'),
    path('excluir/<int:pk>/', views.MusicoDeleteView.as_view(), name='delete'),
]

apresentacao/models.py
from django.db import models

# Create your models here.

apresentacao/views.py
from django import forms
from django.urls import reverse_lazy
from core.models import Apresentacao
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

class ApresentacaoListView(LoginRequiredMixin, ListView):
    model = Apresentacao
    template_name = 'apresentacao/tabela_apresentacao.html'
    context_object_name = 'apresentacoes'
    login_url='login'

class ApresentacaoCreateView(LoginRequiredMixin, CreateView):
    model = Apresentacao
    template_name = 'apresentacao/criar_apresentacao.html'
    fields = ['nome', 'orquestra', 'sinfonia', 'dt_apresentacao']
    success_url = reverse_lazy('apresentacao:read')
    login_url='login'

class ApresentacaoForm(forms.ModelForm):
    class Meta:
        model = Apresentacao
        fields = ['nome', 'orquestra', 'sinfonia', 'dt_apresentacao']
        widgets = {
            'dt_apresentacao': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class ApresentacaoUpdateView(LoginRequiredMixin, UpdateView):
    model = Apresentacao
    template_name = 'apresentacao/criar_apresentacao.html'
    form_class = ApresentacaoForm
    success_url = reverse_lazy('apresentacao:read')
    slug_field = 'id'
    login_url='login'

class ApresentacaoDeleteView(LoginRequiredMixin, DeleteView):
    model = Apresentacao
    success_url = reverse_lazy('apresentacao:read')
    login_url='login'
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

apresentacao/templates/apresentacao/criar_apresentacao.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}



<div class="col-12 d-flex flex-column align-items-center my-4">
    <div class="col-md-6">
        <h3 class="text-center mb-4">Apresentações | {% if object %}Editar{% else %}Adicionar{% endif %}</h3>
    <div class="mt-4">
        <form method="post" action="{% if object %}{% url 'apresentacao:update' object.pk %}{% else %}{% url 'apresentacao:create' %}{% endif %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.nome.id_for_label }}">Nome</label>
                <input class="form-control" id="{{ form.nome.id_for_label }}" type="text"
                    placeholder="Nome" name="{{ form.nome.html_name }}" {% if form.nome.value %}
                    value="{{ form.nome.value }}" {% endif %}>
            </div>

            <div class="form-group">
                <label for="{{ form.orquestra.id_for_label }}">Orquestra</label>
                <select class="form-control" id="{{ form.orquestra.id_for_label }}" name="{{ form.orquestra.html_name }}">
                    {% for orquestra in form.orquestra.field.choices %}
                        <option value="{{ orquestra.0 }}" {% if orquestra.0 == form.orquestra.value %}selected{% endif %}>{{ orquestra.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="{{ form.sinfonia.id_for_label }}">Sinfonia</label>
                <select class="form-control" id="{{ form.sinfonia.id_for_label }}" name="{{ form.sinfonia.html_name }}">
                    {% for sinfonia in form.sinfonia.field.choices %}
                        <option value="{{ sinfonia.0 }}" {% if sinfonia.0 == form.sinfonia.value %}selected{% endif %}>{{ sinfonia.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="{{ form.dt_apresentacao.id_for_label }}">Data e Hora</label>
                <input class="form-control" id="{{ form.dt_apresentacao.id_for_label }}" type="datetime-local"
                    placeholder="Dt. Apresentação" name="{{ form.dt_apresentacao.html_name }}" {% if form.dt_apresentacao.value %}
                    value="{{ form.initial.dt_apresentacao.value|date:'Y-m-d\TH:i' }}" {% endif %}>
                    
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <a href="{% url 'apresentacao:read' %}" class="btn btn-danger ml-3 cancelar-btn">Cancelar</a>
                <button type="submit" class="btn btn-primary salvar-btn">Salvar</button>

                
            </div>
        </form>
    </div>
    </div>
</div>

<style>
    .salvar-btn.btn-primary {
        background-color: #1b80eb; 
        border-color: #1b80eb;
    }
    
    .salvar-btn.btn-primary:hover {
        background-color: #11559e;
        border-color: #11559e;
    }

    .cancelar-btn.btn-danger {
        background-color: #e23a4b;
        border-color: #e23a4b;
    }

    .cancelar-btn.btn-danger:hover {
        background-color: #a82532;
        border-color: #a82532;
    }
</style>

{% endblock %}

apresentacao/templates/apresentacao/tabela_apresentacao.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}
<style>
  .edit-btn {
    color: #1b80eb;
  }

  .edit-btn:hover {
    color: #11559e;
  }

  .delete-btn {
    color: #e23a4b;
  }

  .delete-btn:hover {
    color: #a82532;
  }
</style>
<div class="container table-container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Orquestra</th>
        <th scope="col">Sinfonia</th>
        <th scope="col">Dt. Apresentação</th>
      </tr>
    </thead>
    <tbody>
      {% for a in apresentacoes %}
      <tr>
        <td>{{ a.nome }}</td>
        <td>{{ a.orquestra }}</td>
        <td>{{ a.sinfonia }}</td>
        <td>{{ a.dt_apresentacao }}</td>
        <td>
          <a href="{% url 'apresentacao:update' a.id %}" class="btn btn-link edit-btn" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a href="{% url 'apresentacao:delete' a.id %}" class="btn btn-link delete-btn" title="Excluir">
            <i class="fas fa-trash-alt"></i>
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4" class="text-center">
          <h4>Nada aqui para ver</h4>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="col-12 d-flex justify-content-center mt-16">
    <a href="{% url 'apresentacao:create' %}" class="btn sm action-2 f-16">Adicionar</a>
  </div>
</div>

{% endblock %}