escola_de_musica/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as view
from django.conf.urls.static import static
from core import views
from escola_de_musica import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin:index'),
    path('', views.IndexView.as_view(), name='home'),
    path('sinfonia/', include('sinfonia.urls')),
    path('instrumentos/', include('instrumento.urls')),
    path('orquestras/', include('orquestra.urls')),
    path('apresentacoes/', include('apresentacao.urls')),
    path('musico/', include('musico.urls')),
    path('registrar/', views.registrar, name='registrar'),
    path('login/', views.logar, name='login'),
    path('logout/', view.LogoutView.as_view(next_page='home'), name='logout'),
    path('sobre/', views.SobreView.as_view(), name='sobre'),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musico/urls.py
from django.urls import path
from musico import views

app_name = 'musico'

urlpatterns = [
    path('listar/', views.MusicoListView.as_view(), name='read'),
    path('criar/', views.MusicoCreateView.as_view(), name='create'),
    path('editar/<int:pk>/', views.MusicoUpdateView.as_view(), name='update'),
    path('excluir/<int:pk>/', views.MusicoDeleteView.as_view(), name='delete'),
]

musico/models.py
from django.db import models

# Create your models here.

musico/views.py
from django import forms
from django.urls import reverse_lazy
from core.models import Musico
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class MusicoListView(LoginRequiredMixin, ListView):
    model = Musico
    template_name = 'musico/tabela_musico.html'
    context_object_name = 'musicos'
    login_url='login'

class MusicoCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Musico
    template_name = 'musico/criar_musico.html'
    fields = ['nome', 'nacionalidade', 'dt_nascimento']
    success_url = reverse_lazy('musico:read')
    login_url='login'
    permission_required = 'core.add_musico'

class MusicoForm(forms.ModelForm):
    class Meta:
        model = Musico
        fields = ['nome', 'nacionalidade', 'dt_nascimento']
        widgets = {
            'dt_nascimento': forms.DateInput(attrs={'type': 'date'}),
        }

class MusicoUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Musico
    form_class = MusicoForm
    template_name = 'musico/criar_musico.html'
    success_url = reverse_lazy('musico:read')
    slug_field = 'id'
    login_url='login'
    permission_required = 'core.change_musico'


class MusicoDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Musico
    success_url = reverse_lazy('musico:read')
    login_url='login'
    permission_required = 'core.delete_musico'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

musico/templates/musico/criar_musico.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}

<div class="col-12 d-flex flex-column align-items-center my-4">
    <div class="col-md-6">
        <h3 class="text-center mb-4">Musicos | {% if object %}Editar{% else %}Adicionar{% endif %}</h3>
        <div class="mt-4">
            <form method="post" action="{% if object %}{% url 'musico:update' object.pk %}{% else %}{% url 'musico:create' %}{% endif %}" class="align-items-left">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.nome.id_for_label }}">Nome</label>
                    <input class="form-control" id="{{ form.nome.id_for_label }}" type="text"
                    placeholder="Nome" name="{{ form.nome.html_name }}" {% if form.nome.value %}
                    value="{{ form.nome.value }}" {% endif %}>
                </div>

                <div class="form-group">
                    <label for="{{ form.nacionalidade.id_for_label }}">Nacionalidade</label>
                    <select class="form-control" id="{{ form.nacionalidade.id_for_label }}" name="{{ form.nacionalidade.html_name }}">
                        {% for choice in form.nacionalidade.field.choices %}
                            <option value="{{ choice.0 }}" {% if choice.0 == form.nacionalidade.value %}selected{% endif %}>{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="{{ form.dt_nascimento.id_for_label }}">Dt. Nascimento</label>
                    <input class="form-control" id="{{ form.dt_nascimento.id_for_label }}" type="date"
                        placeholder="01/01/2023" name="{{ form.dt_nascimento.html_name }}"
                        {% if form.instance.dt_nascimento %}
                            value="{{ form.instance.dt_nascimento|date:'Y-m-d' }}"
                        {% endif %}>
                </div>
                
                

                <div class="d-flex justify-content-between align-items-center">
                    <a href="{% url 'musico:read' %}" class="btn btn-danger ml-3 cancelar-btn">Cancelar</a>
                    <button type="submit" class="btn btn-primary salvar-btn">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    .salvar-btn.btn-primary {
        background-color: #1b80eb; 
        border-color: #1b80eb;
    }
    
    .salvar-btn.btn-primary:hover {
        background-color: #11559e;
        border-color: #11559e;
    }

    .cancelar-btn.btn-danger {
        background-color: #e23a4b;
        border-color: #e23a4b;
    }

    .cancelar-btn.btn-danger:hover {
        background-color: #a82532;
        border-color: #a82532;
    }
</style>

{% endblock %}

musico/templates/musico/tabela_musico.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}
<style>
  .edit-btn {
    color: #1b80eb;
  }

  .edit-btn:hover {
    color: #11559e;
  }

  .delete-btn {
    color: #e23a4b;
  }

  .delete-btn:hover {
    color: #a82532;
  }
</style>
<div class="container table-container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Nacionalidade</th>
        <th scope="col">Dt. Nascimento</th>
      </tr>
    </thead>
    <tbody>
      {% for m in musicos %}
      <tr>
        <td>{{ m.nome }}</td>
        <td>{{ m.nacionalidade }}</td>
        <td>{{ m.dt_nascimento }}</td>
        <td>
          <a href="{% url 'musico:update' m.id %}" class="btn btn-link edit-btn" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a href="{% url 'musico:delete' m.id %}" class="btn btn-link delete-btn" title="Excluir">
            <i class="fas fa-trash-alt"></i>
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4" class="text-center">
          <h4>Nada aqui para ver</h4>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="col-12 d-flex justify-content-center mt-16">
    <a href="{% url 'musico:create' %}" class="btn sm action-2 f-16">Adicionar</a>
  </div>
</div>

{% endblock %}