escola_de_musica/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as view
from django.conf.urls.static import static
from core import views
from escola_de_musica import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin:index'),
    path('', views.IndexView.as_view(), name='home'),
    path('sinfonia/', include('sinfonia.urls')),
    path('instrumentos/', include('instrumento.urls')),
    path('orquestras/', include('orquestra.urls')),
    path('apresentacoes/', include('apresentacao.urls')),
    path('musico/', include('musico.urls')),
    path('registrar/', views.registrar, name='registrar'),
    path('login/', views.logar, name='login'),
    path('logout/', view.LogoutView.as_view(next_page='home'), name='logout'),
    path('sobre/', views.SobreView.as_view(), name='sobre'),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musico/urls.py
from django.urls import path
from musico import views

app_name = 'musico'

urlpatterns = [
    path('listar/', views.MusicoListView.as_view(), name='read'),
    path('criar/', views.MusicoCreateView.as_view(), name='create'),
    path('editar/<int:pk>/', views.MusicoUpdateView.as_view(), name='update'),
    path('excluir/<int:pk>/', views.MusicoDeleteView.as_view(), name='delete'),
]

sinfonia/urls.py
from django.urls import path
from sinfonia import views

app_name = 'sinfonia'

urlpatterns = [
    path('listar/', views.SinfoniaListView.as_view(), name='read'),
    path('criar/', views.SinfoniaCreateView.as_view(), name='create'),
    path('editar/<int:pk>/', views.SinfoniaUpdateView.as_view(), name='update'),
    path('excluir/<int:pk>/', views.SinfoniaDeleteView.as_view(), name='delete'),
]

sinfonia/models.py
from django.db import models

# Create your models here.

sinfonia/views.py
from django.urls import reverse_lazy
from core.models import Sinfonia
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class SinfoniaListView(LoginRequiredMixin, ListView):
    model = Sinfonia
    template_name = 'sinfonia/tabela_sinfonia.html'
    context_object_name = 'sinfonias'
    login_url='login'
    

class SinfoniaCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Sinfonia
    template_name = 'sinfonia/criar_sinfonia.html'
    fields = ['nome', 'compositor',]
    success_url = reverse_lazy('sinfonia:read')
    login_url='login'
    permission_required = 'core.add_sinfonia'

class SinfoniaUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Sinfonia
    template_name = 'sinfonia/criar_sinfonia.html'
    fields = ['nome', 'compositor']
    success_url = reverse_lazy('sinfonia:read')
    slug_field = 'id'
    login_url='login'
    permission_required = 'core.change_sinfonia'

class SinfoniaDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Sinfonia
    success_url = reverse_lazy('sinfonia:read')
    login_url='login'
    permission_required = 'core.delete_sinfonia'
    
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

sinfonia/templates/sinfonia/criar_sinfonia.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}

<div class="col-12 d-flex flex-column align-items-center my-4">
    <div class="col-md-6">
        <h3 class="text-center mb-4">Sinfonias | {% if object %}Editar{% else %}Adicionar{% endif %}</h3>
    <div class="mt-4">
        <form method="post" action="{% if object %}{% url 'sinfonia:update' object.pk %}{% else %}{% url 'sinfonia:create' %}{% endif %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.nome.id_for_label }}">Nome</label>
                <input class="form-control" id="{{ form.nome.id_for_label }}" type="text"
                    placeholder="Nome" name="{{ form.nome.html_name }}" {% if form.nome.value %}
                    value="{{ form.nome.value }}" {% endif %}>
            </div>

            <div class="form-group">
                <label for="{{ form.compositor.id_for_label }}">Compositor</label>
                <select class="form-control" id="{{ form.musico.id_for_label }}" name="{{ form.compositor.html_name }}">
                    {% for compositor in form.compositor.field.choices %}
                        <option value="{{ compositor.0 }}" {% if compositor.0 == form.compositor.value %}selected{% endif %}>{{ compositor.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="d-flex justify-content-between align-items-center">
                <a href="{% url 'sinfonia:read' %}" class="btn btn-danger ml-3 cancelar-btn">Cancelar</a>
                <button type="submit" class="btn btn-primary salvar-btn">Salvar</button>
            </div>
        </form>
    </div>
    </div>
</div>

<style>
    .salvar-btn.btn-primary {
        background-color: #1b80eb; 
        border-color: #1b80eb;
    }
    
    .salvar-btn.btn-primary:hover {
        background-color: #11559e;
        border-color: #11559e;
    }

    .cancelar-btn.btn-danger {
        background-color: #e23a4b;
        border-color: #e23a4b;
    }

    .cancelar-btn.btn-danger:hover {
        background-color: #a82532;
        border-color: #a82532;
    }
</style>

{% endblock %}

sinfonia/templates/sinfonia/tabela_sinfonia.html
{% extends "base.html" %} 
{% block content %} 
{% include 'components/nav_tables.html' %}
<style>
  .edit-btn {
    color: #1b80eb;
  }

  .edit-btn:hover {
    color: #11559e;
  }

  .delete-btn {
    color: #e23a4b;
  }

  .delete-btn:hover {
    color: #a82532;
  }
</style>
<div class="container table-container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Compositor</th>
        <th scope="col">Dt. Criação</th>
      </tr>
    </thead>
    <tbody>
      {% for sinf in sinfonias %}
      <tr>
        <td>{{ sinf.nome }}</td>
        <td>{{ sinf.compositor }}</td>
        <td>{{ sinf.dt_criacao }}</td>
        <td>
          <a href="{% url 'sinfonia:update' sinf.id %}" class="btn btn-link edit-btn" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a href="{% url 'sinfonia:delete' sinf.id %}" class="btn btn-link delete-btn" title="Excluir">
            <i class="fas fa-trash-alt"></i>
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4" class="text-center">
          <h4>Nada aqui para ver</h4>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="col-12 d-flex justify-content-center mt-16">
    <a href="{% url 'sinfonia:create' %}" class="btn sm action-2 f-16">Adicionar</a>
  </div>
</div>

{% endblock %}